Importando biblioteca "pandas" e organizando o DataSet

In [29]:
import pandas as pd

#Utilizei o sep, para o pandas verificar que a separação é ";"
df = pd.read_csv("cidades_vacinacao.csv", encoding = "utf-8", sep = ";")

df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145
0,Abadiânia,18.0,16/02/2022,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abadiânia,18.0,16/02/2022,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abadiânia,18.0,16/02/2022,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abadiânia,18.0,16/02/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abadiânia,18.0,16/02/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Limpando as colunas vazias

In [31]:
df = df.dropna(axis=1, how='all')

In [32]:
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,16/02/2022,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,16/02/2022,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18.0,16/02/2022,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18.0,16/02/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18.0,16/02/2022,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

Verificando informações do DataSet

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1444 entries, 0 to 1443
Data columns (total 20 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Município de vacinação                              444 non-null    str
 1   Idade Evento                                        444 non-null    float64
 2   Data da Notificação                                 444 non-null    str
 3   Raça/Cor                                            444 non-null    str
 4   Sexo                                                444 non-null    str
 5   Imunobiológico (vacina)                             444 non-null    str
 6   Dose                                                443 non-null    str
 7   Gestante                                            444 non-null    str
 8   Mês de gestação                                     444 non-null    float64
 9   Mulher amamentando no momento da vacinação?         444 non-null    str
 10  Tipo de Evento                                      444 non-null    str
 11  Reação / evento adverso                             438 non-null    str
 12  Classificação de gravidade                          443 non-null    str
 13  Gravidade                                           444 non-null    str
 14  Desfecho (evolução do caso)                         443 non-null    str
 15  Doenças (CID10) - Preexistente                      407 non-null    str
 16  Medicamento em uso anterior ou durante a vacinação  283 non-null    str
 17  Nome do Medicamento                                 444 non-null    str
 18  Houve atendimento médico?                           444 non-null    str
 19  Tipo de Atendimento                                 444 non-null    str
dtypes: float64(2), str(18)
memory usage: 225.8 KB

Alterando "Data de notificação" para o Tipo "Date"

In [36]:
df['Data da Notificação'] = pd.to_datetime(df['Data da Notificação'], dayfirst=False, errors ="coerce")

print(df.dtypes)

Município de vacinação                                           str
Idade Evento                                                 float64
Data da Notificação                                   datetime64[us]
Raça/Cor                                                         str
Sexo                                                             str
Imunobiológico (vacina)                                          str
Dose                                                             str
Gestante                                                         str
Mês de gestação                                              float64
Mulher amamentando no momento da vacinação?                      str
Tipo de Evento                                                   str
Reação / evento adverso                                          str
Classificação de gravidade                                       str
Gravidade                                                        str
Desfecho (evolução do caso)                                      str
Doenças (CID10) - Preexistente                                   str
Medicamento em uso anterior ou durante a vacinação               str
Nome do Medicamento                                              str
Houve atendimento médico?                                        str
Tipo de Atendimento                                              str
dtype: object

/tmp/ipykernel_4361/755518877.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Data da Notificação'] = pd.to_datetime(df['Data da Notificação'], dayfirst=False, errors ="coerce")

Alterando "Idade de Evento" para o tipo "Inteiro"

In [40]:
df['Idade Evento'] = pd.to_numeric(df['Idade Evento'], errors='coerce')

print(df.dtypes)

Município de vacinação                                           str
Idade Evento                                                 float64
Data da Notificação                                   datetime64[us]
Raça/Cor                                                         str
Sexo                                                             str
Imunobiológico (vacina)                                          str
Dose                                                             str
Gestante                                                         str
Mês de gestação                                              float64
Mulher amamentando no momento da vacinação?                      str
Tipo de Evento                                                   str
Reação / evento adverso                                          str
Classificação de gravidade                                       str
Gravidade                                                        str
Desfecho (evolução do caso)                                      str
Doenças (CID10) - Preexistente                                   str
Medicamento em uso anterior ou durante a vacinação               str
Nome do Medicamento                                              str
Houve atendimento médico?                                        str
Tipo de Atendimento                                              str
dtype: object

In [42]:
df.head()

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Imunobiológico (vacina),Dose,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,Classificação de gravidade,Gravidade,Desfecho (evolução do caso),Doenças (CID10) - Preexistente,Medicamento em uso anterior ou durante a vacinação,Nome do Medicamento,Houve atendimento médico?,Tipo de Atendimento
0,Abadiânia,18.0,2022-02-16,Branca,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
1,Abadiânia,18.0,2022-02-16,Parda,Masculino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
2,Abadiânia,18.0,2022-02-16,Parda,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: - 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
3,Abadiânia,18.0,2022-02-16,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose / 2: 2ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0
4,Abadiânia,18.0,2022-02-16,Branca,Feminino,1: Astrazeneca/Fiocruz,1: 1ª Dose,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,1: Não grave,0,1: Cura sem sequelas,0,Não,Não,Não,0

Salvando planilha limpa

In [44]:
df.to_csv("cidade_vacinacao_limpa.csv")